version: '3'

services:
  db:
    image: postgres
    command: "-c logging_collector=on -c log_statement=all -c log_directory=/var/log/postgresql/"
    environment:
      POSTGRES_USER: "dlserver"
      POSTGRES_PASSWORD: "dlserver"
      POSTGRES_DB: "dlserver"
    volumes:
      - postgresdata:/var/lib/postgresql/data

  django:
    build:
      context: .
      dockerfile: deploy/Dockerfile
    volumes:
      - ./uploads:/app/uploads
      - ./sock:/app/sock
    depends_on:
      - db
    links:
      - db
    environment:
      - ENV=docker

volumes:
  postgresdata: